# POST http://localhost:5000/api/users/login
# Content-Type: application/json


# {
#     "email": "test@gmail.com",
#     "password": "User@123456"
# }

POST http://localhost:5000/api/photographers/create

Content-Type: application/json

{
  "name": "test_grapher",
  "id":"Test-01",
  "contactNumber":"7975942038",
  "email": "ps.pannaga@deepcognition.ai",
}